module.exports = {
pen : " 钢笔 ",
pencil : " 铅笔 ",
ruler : " 尺子",
eraser : " 橡皮 ",
crayon : " 蜡笔 ",
book : " 书 ",
bag : " 书包",
sharpener : " 卷笔刀 ",
school : " 学校",
head : " 头",
face : " 脸 ",
nose : " 鼻子 ",
mouth : " 嘴 ",
eye : "眼睛 ",
ear : " 耳朵",
arm : " 胳膊 ",
finger : " 手指 ",
leg : " 腿 ",
foot : " 脚 ",
body : " 身体",
red : " 红色的 ",
yellow : " 黄色的 ",
green : " 绿色的 ",
blue : " 蓝色的",
purple : " 紫色的",
white :  "白色的 ",
black : " 黑色的",
orange : " 橙色的",
pink : " 粉色的 ",
brown : " 棕色的",
cat : " 猫 ",
dog : " 狗",
monkey : " 猴子 ",
panda : " 熊猫",
rabbit : " 兔子 ",
duck : " 鸭子 ",
pig : " 猪",
bird : " 鸟",
bear : " 熊 ",
elephant : " 大象",
mouse : " 老鼠",
squirrel : " 松鼠",
cake : " 蛋糕",
bread : " 面包 ",
hamburger : " 汉堡包",
chicken : " 鸡肉",
tea : " 茶",
Coke : " 可乐",
juice : " 果汁",
milk : " 牛奶",
water : " 水",
coffee : " 咖啡",
one : " 一 ",
two : " 二 ",
three : " 三 ",
four : " 四 ",
five : " 五",
six : " 六 ",
seven : " 七 ",
eight : " 八 ",
nine : " 九 ",
ten : " 十",
doll : " 玩具娃娃 ",
boat : " 小船 ",
ball : " 球 ",
kite : " 风筝",
balloon : " 气球",
car : " 小汽车",
plane : " 飞机",
boy : " 男孩 ",
girl : " 女孩 ",
teacher : " 教师 ",
student : " 学生",
this : " 这个",
my : " 我的",
friend : " 朋友",
nice : " 好的",
meet : " 遇见",
goodbye : " 再见",
too : " 太",
father : " 父亲",
dad : " 爸爸",
mother : " 母亲 ",
mom : " 妈妈",
man男人 : " ",
woman : " 女人 ",
grandmother : " 祖母",
grandma : " 祖母",
grandfather : " (外)祖父 ",
grandpa : " (口语)(外)祖父 ",
sister : " 姐妹",
brother : " 兄弟 ",
great : " 太好了",
really : " 真地;确切地 ",
and : " 和 ",
how : " 多么",
eleven : " 十一",
twelve : " 十二 ",
thirteen : " 十三 ",
fourteen : " 十四　　",
fifteen : " 十五 ",
sixteen : " 十六 ",
seventeen : " 十七 ",
eighteen : " 十八",
nineteen : " 十九 ",
twenty : " 二十 ",
how : " many 多少 ",
can : " 能够;可以 ",
look : " at 看;瞧",
peach : " 桃 ",
pear : " 梨 ",
orange : " 橙子 ",
watermelon : " 西瓜",
apple : " 苹果 ",
banana : " 香蕉 ",
strawberry : " 草莓 ",
grape : " 葡萄",
like : " 喜欢",
some : " 一些;某些",
thanks : " 多谢",
bus : " 公共汽车 ",
bike : " 自行车 ",
taxi : " 出租车 ",
jeep : " 吉普车",
desk : " 课桌",
chair : " 椅子 ",
walkman : " 随身听 ",
lamp : " 台灯 ",
your : " 你的;你们的 ",
zoo : " 动物园",
small : " 小的 ",
big : " 大的 ",
long : " 长的 ",
short : " 短的;矮的",
tall : " 高的 ",
giraffe : " 长颈鹿 ",
deer : " 鹿",
Window : " 窗户 ",
board : " 板",
light : " 灯",
picture : " 图片 ",
door : " 门 ",
floor : " 地板 ",
classroom : " 教室",
computer : " 电脑",
wall : " 墙 ",
fan : " 扇子",
bag : " 包 ",
pencil : " 铅笔",
pen : " 钢笔  ",
book : " 书",
ruler : " 尺子 ",
teacher : " 教师 ",
student : " 学生 ",
boy : " 男孩 ",
girl : " 女孩 ",
friend : " 朋友",
home : " 家",
room : " 房间 ",
school : " 学校 ",
classroom : " 教室",
window : " 窗户 ",
desk : " 课桌;书桌 ",
door : " 门 ",
chair : " 椅子 ",
bed : " 床",
rice : " 米饭",
beef : " 牛肉 ",
bread : " 面包 ",
milk : " 牛奶",
egg : " 蛋",
water : " 水",
chicken : " 鸡肉",
fish : " 鱼",
sister : " 姐妹",
brother : " 兄弟",
father : " 父亲;爸爸）",
mother : " 母亲;妈妈",
driver : " 司机",
doctor : " 医生",
farmer : " 农民",
nurse : " 护士",
computer : " 计算机",
board : " 写字板",
fan : " 风扇",
light : " 灯",
this : " 这;这个",
is : " 是",
my : " 我的",
that : " 那;那个",
your : " 你的",
picture : " 图画;照片",
wall : " 墙壁",
floor : " 地板",
yes : " 是;是的",
it : " 它",
what : " 什么 ",
time : " 时间",
math : " 数学",
Chinese : " 语文 ",
English : " 英语 ",
music : " 音乐 ",
for : " 为;给 ",
class : " 课程",
jacket : " 夹克衫 ",
shirt : " 衬衫 ",
skirt : " 裙子 ",
dress : " 连衣裙",
red : " 红色的 ",
blue : " 蓝色的 ",
yellow : " 黄色的",
green : " 绿色的 ",
white : " 白色的 ",
no : " 不;不是 ",
not : " 不;不是的 ",
color : " 颜色",
warm : " 暖和的",
cold : " 寒冷的 ",
cool : " 凉爽的 ",
today : " 今天",
jeans : " 牛仔裤",
pants : " 长裤",
socks : " 袜子 ",
shoes : " 鞋子",
football : " 足球 ",
snowy : " 下雪的 ",
sunny : " 晴朗的",
big : " 大的 ",
small : " 小的 ",
long : " 长的",
short : " 短的 ",
apple : " 苹果 ",
banana : " 香蕉 ",
pear : " 梨",
orange : " 橙子 ",
watermelon : " 西瓜 ",
are : " 是 ",
they它 : " 他、她们",
horse : " 马 ",
cat : " 猫 ",
rabbit : " 兔子",
pig : " 猪 ",
duck : " 鸭子 ",
dog : " 狗 ",
eleven : " 十一",
twelve : " 十二 ",
thirteen : " 十三 ",
fifteen : " 十五 ",
twenty : " 二十",
there : " 那儿;那里",
Young : " 年轻的 ",
funny : " 滑稽可笑的 ",
tall : " 高的　",
strong : " 强壮的",
kind : " 和蔼的;亲切的 ",
old : " 年老的 ",
short : " 矮的 ",
thin : " 瘦的",
Mr : " 先生　",
like : " 像;喜欢 ",
strict : " 严格的 ",
smart : " 聪明的;巧妙的",
active : " 积极的;活跃的 ",
quiet : " 安静的;文静的 ",
very : " 很;非常 ",
but : " 但是",
Monday : " 星期一 ",
Tuesday : " 星期二 ",
Wednesday : " 星期三 ",
Thursday : " 星期四",
Friday : " 星期五 ",
Saturday : " 星期六 ",
Sunday : " 星期天 ",
day : " 天;日子",
have : " 有;吃 ",
on : " 在…..时候 ",
eggplant : " 茄子 ",
fish : " 鱼 ",
tofu : " 豆腐",
potato : " 土豆 ",
tomato : " 西红柿 ",
for : " 为;给 ",
lunch : " 中餐;午饭",
we : " 我们 ",
tasty : " 好吃的　",
sweet : " 甜的 ",
sour : " 酸的",
fresh : " 新鲜的 ",
salty : " 咸的 ",
favourite : " 最喜爱的;特别喜爱的",
fruit : " 水果 ",
grape : " 葡萄",
curtain : " 空调 ",
closet : " 壁橱 ",
mirror : " 镜子",
bedroom : " 卧室 ",
kitchen : " 厨房 ",
bathroom : " 卫生间",
in : " 在…里面 ",
on : " 在…上面 ",
under : " 在…下面",
near : " 在..旁边 ",
behind : " 在…后边 ",
clothes : " 衣服",
river : " 河流 ",
flower : " 花 ",
grass : " 草 ",
lake : " 湖泊",
forest : " 森林 ",
path : " 路 ",
park : " 公园 ",
picture : " 照片",
house : " 房子 ",
bridge : " 桥 ",
tree : " 树 ",
road : " 公路",
building : " 建筑物 ",
clean : " 干净的",
spring : " 春天",
summer : " 夏天",
fall : " 秋天 ",
winter : " 冬天",
season季节 : " ",
which : " 哪一个 ",
best : " 最;极 ",
swim : " 游泳",
skate : " 滑冰;滑冰鞋　",
why : " 为什么 ",
because : " 因为 ",
sleep : " 睡觉",
January : " 一月 ",
February : " 二月 ",
March : " 三月 ",
April : " 四月",
May : " 五月 ",
June : " 六月 ",
July : " 七月 ",
August : " 八月 ",
September : " 九月",
October : " 十月",
November : " 十一月 ",
December : " 十二月",
birthday : " 生日 ",
uncle : " 叔叔;舅舅 ",
her : " 她的 ",
date : " 日期",
mom : " 妈妈 ",
grandpa : " 爷爷;外公 ",
study : " 书房",
fly : " 飞 ",
jump : " 跳 ",
walk : " 走 ",
run : " 跑 ",
swim : " 游泳",
kangaroo : " 袋鼠",
sleep : " 睡觉",
climb : " 往上爬",
fight : " 打架",
swing : " 荡;荡秋千",
by : " 经，乘",
foot : " 脚 ",
bike : " 自行车 ",
bus : " 公共汽车 ",
wait : " 等待",
train : " 火车 ",
how : " 怎样 ",
traffic : " 交通 ",
stop : " 停，停车站",
library : " 图书馆 ",
hospital : " 医院 ",
cinema : " 电影院",
turn : " 转弯 ",
bookstore : " 书店 ",
where : " 在哪里，到哪里 ",
please : " 请",
right : "  右边 ",
left : " 左边",
straight : " 成直线地 ",
then : "  然后",
newspaper : " 报纸 ",
buy : " 购买",
hobby : " 爱好  ",
dive : " 跳水",
live : " 居住 ",
teach : " 教",
go : " 去 ",
watch : " 看 ",
read : " 读，看",
singer : " 歌唱家，歌手 ",
writer : " 作家 ",
actor : " 男演员 ",
actress : " 女演员",
artist : " 画家 ",
engineer : " 工程师 ",
accountant : " 会计",
policeman : " 男警察 ",
salesperson : " 销售员 ",
cleaner : " 清洁工",
where : " 在哪里，到哪里 ",
work : " 工作",
rain : " 雨 ",
cloud : " 云 ",
sun : " 太阳 ",
stream : " 河，溪",
seed : " 种子 ",
soil : " 土壤 ",
sprout : " 苗，芽",
plant : " 植物，种植 ",
should : " 应该 ",
then : " 然后",
}